DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia3lsZSIsImlhdCI6MTc1MTI2NTUxMH0.ALfH0PeDyNK0_rDwtgz5c1gaQlEf5YDJFc7VXr0rkcM"
}

